/**
 * A catalogue of real, external online courses — the "browse and discover" library,
 * separate from the five internal MoSPI competency pathways in `./courses.ts`.
 *
 * Why this is its own file, and its own type. `courses.ts` describes the handful of
 * pathways the platform itself teaches against a competency, with module outlines and
 * the standing warning that no lesson content ships. This file is the opposite kind of
 * thing: pointers *out* to courses that already exist on Coursera, edX, MIT
 * OpenCourseWare, freeCodeCamp and the like. Nothing here is hosted by NEXORA AI, and
 * every row is a link a learner follows to another site. Keeping the two apart means the
 * recommendation engine, the competency scoring and their tests never have to know this
 * catalogue exists.
 *
 *   Honesty about the data
 *
 * These are genuine courses from named providers, and every `url` points at that
 * provider's own canonical page for the course. Providers do restructure their sites
 * and retire courses, so a link should be re-checked before a public launch — the
 * `verifyLinks` note below says how. Durations are the provider's own estimate where one
 * is published and a considered approximation otherwise; every one is at least one hour,
 * which is the floor this catalogue promises. Ratings are omitted rather than invented:
 * a number no one measured would be exactly the kind of decoration the rest of this
 * project refuses to ship.
 */

export type CourseCategory = 'engineering' | 'medical' | 'data-science' | 'business';

export type CourseLevel = 'Beginner' | 'Intermediate' | 'Advanced' | 'All levels';

/**
 * What it costs to take. "Free to audit" is Coursera/edX's model — the material is free,
 * a certificate is paid — and is kept distinct from "Free" (freeCodeCamp, MIT OCW, NPTEL)
 * because the two are a real difference to a learner deciding where to spend an evening.
 */
export type CourseCost = 'Free' | 'Free to audit' | 'Paid' | 'Subscription';

export type ExternalCourse = {
  /** Unique kebab-case slug, used as a React key and in any saved-course record. */
  id: string;
  title: string;
  /** The platform the link lands on: Coursera, edX, MIT OpenCourseWare, freeCodeCamp… */
  provider: string;
  /** The university or company that authored it, e.g. "Stanford", "Google", "IIT Madras". */
  partner: string;
  category: CourseCategory;
  /** The finer topic, for the on-card label and search: "Machine learning", "Cardiology". */
  subject: string;
  level: CourseLevel;
  /** Approximate total hours. Always ≥ 1 — the catalogue's floor. */
  hours: number;
  cost: CourseCost;
  /** Whether a certificate is available (often paid even when the course is free to audit). */
  certificate: boolean;
  /** True for the courses in highest demand right now, surfaced in the "Trending" filter. */
  trending: boolean;
  /** The provider's own canonical page for this course. */
  url: string;
  /** One line: what the course is and who it is for. */
  blurb: string;
};

/**
 * Shown wherever the catalogue appears. It is not the same disclaimer as `catalogueNote`
 * in `./courses.ts`: that one says "no lessons ship"; this one says "these lead off-site
 * and are not ours", which is the honest thing to tell a learner about an external link.
 */
export const libraryNote =
  'These are real courses hosted by external providers. NEXORA AI does not host or endorse them; links open on the provider’s site and may change over time.';

/* ----------------------------------------------------------------- engineering */

const engineering: ExternalCourse[] = [
  {
    id: 'cs50x',
    title: "CS50: Introduction to Computer Science",
    provider: 'edX',
    partner: 'Harvard University',
    category: 'engineering',
    subject: 'Computer science',
    level: 'Beginner',
    hours: 100,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.edx.org/learn/computer-science/harvard-university-cs50-s-introduction-to-computer-science',
    blurb: "Harvard's flagship intro to CS: C, Python, SQL, algorithms and web basics, taught from first principles.",
  },
  {
    id: 'python-for-everybody',
    title: 'Python for Everybody',
    provider: 'Coursera',
    partner: 'University of Michigan',
    category: 'engineering',
    subject: 'Programming',
    level: 'Beginner',
    hours: 80,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/specializations/python',
    blurb: 'The most-taken beginner Python track: syntax, data structures, web scraping, APIs and databases.',
  },
  {
    id: 'cs50-web',
    title: 'CS50 Web Programming with Python and JavaScript',
    provider: 'edX',
    partner: 'Harvard University',
    category: 'engineering',
    subject: 'Web development',
    level: 'Intermediate',
    hours: 90,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.edx.org/learn/web-development/harvard-university-cs50-s-web-programming-with-python-and-javascript',
    blurb: 'Django, JavaScript, SQL and front-end design, building real deployable web applications.',
  },
  {
    id: 'meta-frontend',
    title: 'Meta Front-End Developer Professional Certificate',
    provider: 'Coursera',
    partner: 'Meta',
    category: 'engineering',
    subject: 'Web development',
    level: 'Beginner',
    hours: 140,
    cost: 'Paid',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/professional-certificates/meta-front-end-developer',
    blurb: 'React, HTML, CSS and JavaScript to job-ready standard, built and graded by Meta engineers.',
  },
  {
    id: 'meta-backend',
    title: 'Meta Back-End Developer Professional Certificate',
    provider: 'Coursera',
    partner: 'Meta',
    category: 'engineering',
    subject: 'Web development',
    level: 'Intermediate',
    hours: 140,
    cost: 'Paid',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/professional-certificates/meta-back-end-developer',
    blurb: 'Python, Django, APIs and databases for server-side development, with a capstone project.',
  },
  {
    id: 'full-stack-open',
    title: 'Full Stack Open',
    provider: 'University of Helsinki',
    partner: 'University of Helsinki',
    category: 'engineering',
    subject: 'Web development',
    level: 'Intermediate',
    hours: 100,
    cost: 'Free',
    certificate: true,
    trending: true,
    url: 'https://fullstackopen.com/en/',
    blurb: 'A deep modern JavaScript stack: React, Redux, Node, GraphQL, TypeScript and testing. Free, no ads.',
  },
  {
    id: 'odin-project',
    title: 'The Odin Project: Full Stack JavaScript',
    provider: 'The Odin Project',
    partner: 'The Odin Project',
    category: 'engineering',
    subject: 'Web development',
    level: 'Beginner',
    hours: 120,
    cost: 'Free',
    certificate: false,
    trending: false,
    url: 'https://www.theodinproject.com/paths/full-stack-javascript',
    blurb: 'A free, project-heavy path from zero to full-stack, widely used by self-taught developers.',
  },
  {
    id: 'fcc-responsive-web',
    title: 'Responsive Web Design Certification',
    provider: 'freeCodeCamp',
    partner: 'freeCodeCamp',
    category: 'engineering',
    subject: 'Web development',
    level: 'Beginner',
    hours: 30,
    cost: 'Free',
    certificate: true,
    trending: false,
    url: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
    blurb: 'HTML and CSS through building real layouts, including flexbox, grid and accessibility.',
  },
  {
    id: 'fcc-js-algorithms',
    title: 'JavaScript Algorithms and Data Structures',
    provider: 'freeCodeCamp',
    partner: 'freeCodeCamp',
    category: 'engineering',
    subject: 'Programming',
    level: 'Beginner',
    hours: 40,
    cost: 'Free',
    certificate: true,
    trending: false,
    url: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/',
    blurb: 'JavaScript fundamentals, algorithmic thinking and data structures, entirely hands-on.',
  },
  {
    id: 'mit-6006-algorithms',
    title: '6.006 Introduction to Algorithms',
    provider: 'MIT OpenCourseWare',
    partner: 'MIT',
    category: 'engineering',
    subject: 'Algorithms',
    level: 'Advanced',
    hours: 60,
    cost: 'Free',
    certificate: false,
    trending: false,
    url: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    blurb: 'MIT lectures, notes and problem sets on the core algorithms every engineer should know.',
  },
  {
    id: 'princeton-algorithms-1',
    title: 'Algorithms, Part I',
    provider: 'Coursera',
    partner: 'Princeton University',
    category: 'engineering',
    subject: 'Algorithms',
    level: 'Intermediate',
    hours: 54,
    cost: 'Free',
    certificate: false,
    trending: false,
    url: 'https://www.coursera.org/learn/algorithms-part1',
    blurb: "Sedgewick and Wayne's classic: sorting, searching, union-find and data structures in Java.",
  },
  {
    id: 'mit-6001-python',
    title: '6.0001 Introduction to Computer Science and Programming in Python',
    provider: 'MIT OpenCourseWare',
    partner: 'MIT',
    category: 'engineering',
    subject: 'Programming',
    level: 'Beginner',
    hours: 40,
    cost: 'Free',
    certificate: false,
    trending: false,
    url: 'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/',
    blurb: 'A rigorous first programming course from MIT, with lecture videos and graded problem sets.',
  },
  {
    id: 'google-it-support',
    title: 'Google IT Support Professional Certificate',
    provider: 'Coursera',
    partner: 'Google',
    category: 'engineering',
    subject: 'IT & networking',
    level: 'Beginner',
    hours: 120,
    cost: 'Paid',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/professional-certificates/google-it-support',
    blurb: 'Networking, operating systems, system administration and security for an entry IT role.',
  },
  {
    id: 'aws-cloud-practitioner',
    title: 'AWS Cloud Practitioner Essentials',
    provider: 'Coursera',
    partner: 'Amazon Web Services',
    category: 'engineering',
    subject: 'Cloud computing',
    level: 'Beginner',
    hours: 15,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/learn/aws-cloud-practitioner-essentials',
    blurb: 'A cloud-fundamentals course from AWS itself, and the standard on-ramp to its certifications.',
  },
  {
    id: 'azure-fundamentals-az900',
    title: 'Microsoft Azure Fundamentals (AZ-900)',
    provider: 'Microsoft Learn',
    partner: 'Microsoft',
    category: 'engineering',
    subject: 'Cloud computing',
    level: 'Beginner',
    hours: 10,
    cost: 'Free',
    certificate: true,
    trending: true,
    url: 'https://learn.microsoft.com/en-us/training/courses/az-900t00/',
    blurb: 'Core cloud concepts and Azure services, the official prep for the AZ-900 exam.',
  },
  {
    id: 'gcp-fundamentals',
    title: 'Google Cloud Fundamentals: Core Infrastructure',
    provider: 'Coursera',
    partner: 'Google Cloud',
    category: 'engineering',
    subject: 'Cloud computing',
    level: 'Beginner',
    hours: 12,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/gcp-fundamentals',
    blurb: 'A tour of Google Cloud compute, storage and networking, with hands-on labs.',
  },
  {
    id: 'docker-kubernetes',
    title: 'Docker and Kubernetes: The Complete Guide',
    provider: 'Udemy',
    partner: 'Stephen Grider',
    category: 'engineering',
    subject: 'DevOps',
    level: 'Intermediate',
    hours: 22,
    cost: 'Paid',
    certificate: true,
    trending: true,
    url: 'https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/',
    blurb: 'Containers, images and orchestration end to end, building and deploying real services.',
  },
  {
    id: 'nptel-programming-c',
    title: 'Introduction to Programming in C',
    provider: 'NPTEL',
    partner: 'IIT Kanpur',
    category: 'engineering',
    subject: 'Programming',
    level: 'Beginner',
    hours: 40,
    cost: 'Free',
    certificate: true,
    trending: false,
    url: 'https://nptel.ac.in/courses/106104128',
    blurb: 'A rigorous C programming course from the IITs, with weekly assignments and a proctored exam option.',
  },
  {
    id: 'nptel-dsa',
    title: 'Data Structures and Algorithms',
    provider: 'NPTEL',
    partner: 'IIT Madras',
    category: 'engineering',
    subject: 'Algorithms',
    level: 'Intermediate',
    hours: 48,
    cost: 'Free',
    certificate: true,
    trending: false,
    url: 'https://nptel.ac.in/courses/106106145',
    blurb: 'Core data structures and algorithm design from IIT faculty, a staple of Indian CS preparation.',
  },
  {
    id: 'gt-engineering-mechanics',
    title: 'Introduction to Engineering Mechanics',
    provider: 'Coursera',
    partner: 'Georgia Institute of Technology',
    category: 'engineering',
    subject: 'Mechanical engineering',
    level: 'Beginner',
    hours: 20,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/engineering-mechanics-statics',
    blurb: 'Statics and the analysis of forces and equilibrium, the foundation of mechanical and civil work.',
  },
  {
    id: 'matlab-vanderbilt',
    title: 'Introduction to Programming with MATLAB',
    provider: 'Coursera',
    partner: 'Vanderbilt University',
    category: 'engineering',
    subject: 'Engineering computing',
    level: 'Beginner',
    hours: 33,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/matlab',
    blurb: 'MATLAB from the ground up, the tool most engineering degrees build their computing around.',
  },
  {
    id: 'gt-electronics',
    title: 'Introduction to Electronics',
    provider: 'Coursera',
    partner: 'Georgia Institute of Technology',
    category: 'engineering',
    subject: 'Electrical engineering',
    level: 'Intermediate',
    hours: 41,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/electronics',
    blurb: 'Diodes, transistors and op-amps: the analog electronics an EE student meets first.',
  },
  {
    id: 'mit-6002-circuits',
    title: '6.002 Circuits and Electronics',
    provider: 'MIT OpenCourseWare',
    partner: 'MIT',
    category: 'engineering',
    subject: 'Electrical engineering',
    level: 'Advanced',
    hours: 50,
    cost: 'Free',
    certificate: false,
    trending: false,
    url: 'https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/',
    blurb: "MIT's foundational circuits course: lumped elements, amplifiers and first-order systems.",
  },
  {
    id: 'penn-robotics',
    title: 'Robotics Specialization',
    provider: 'Coursera',
    partner: 'University of Pennsylvania',
    category: 'engineering',
    subject: 'Robotics',
    level: 'Advanced',
    hours: 80,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/specializations/robotics',
    blurb: 'Aerial robotics, mobility, perception, estimation and control, from the GRASP lab at Penn.',
  },
  {
    id: 'toronto-self-driving',
    title: 'Self-Driving Cars Specialization',
    provider: 'Coursera',
    partner: 'University of Toronto',
    category: 'engineering',
    subject: 'Autonomous systems',
    level: 'Advanced',
    hours: 80,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/specializations/self-driving-cars',
    blurb: 'State estimation, perception, planning and control for autonomous vehicles, with CARLA simulation.',
  },
  {
    id: 'ucsd-iot',
    title: 'An Introduction to Programming the Internet of Things (IoT)',
    provider: 'Coursera',
    partner: 'UC San Diego',
    category: 'engineering',
    subject: 'Embedded & IoT',
    level: 'Intermediate',
    hours: 96,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/specializations/iot',
    blurb: 'Arduino, Raspberry Pi and networked devices, building a connected system end to end.',
  },
  {
    id: 'utexas-embedded',
    title: 'Embedded Systems - Shape the World',
    provider: 'edX',
    partner: 'University of Texas at Austin',
    category: 'engineering',
    subject: 'Embedded & IoT',
    level: 'Intermediate',
    hours: 90,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.edx.org/learn/electronics/the-university-of-texas-at-austin-embedded-systems-shape-the-world-microcontroller-input-output',
    blurb: 'Microcontroller I/O with real hardware, wiring interrupts, ADCs and finite-state machines.',
  },
  {
    id: 'michigan-thermodynamics',
    title: 'Introduction to Thermodynamics: Transferring Energy from Here to There',
    provider: 'Coursera',
    partner: 'University of Michigan',
    category: 'engineering',
    subject: 'Mechanical engineering',
    level: 'Intermediate',
    hours: 20,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/thermodynamics-intro',
    blurb: 'The first law, energy and work, applied to engines and real thermal systems.',
  },
  {
    id: 'columbia-construction-management',
    title: 'Construction Management Specialization',
    provider: 'Coursera',
    partner: 'Columbia University',
    category: 'engineering',
    subject: 'Civil engineering',
    level: 'Intermediate',
    hours: 60,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/specializations/construction-management',
    blurb: 'Project initiation, scheduling, cost control and finance for civil and building projects.',
  },
  {
    id: 'autodesk-cad-fusion',
    title: 'Autodesk CAD/CAM/CAE for Mechanical Engineering',
    provider: 'Coursera',
    partner: 'Autodesk',
    category: 'engineering',
    subject: 'CAD & design',
    level: 'Intermediate',
    hours: 60,
    cost: 'Paid',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/specializations/autodesk-cad-cam-cae-mechanical-engineering',
    blurb: 'Model, simulate and prepare parts for manufacture in Fusion 360, taught by Autodesk.',
  },
  {
    id: 'suny-solar-energy',
    title: 'Solar Energy Basics',
    provider: 'Coursera',
    partner: 'SUNY / University at Buffalo',
    category: 'engineering',
    subject: 'Energy engineering',
    level: 'Beginner',
    hours: 10,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/solar-energy-basics',
    blurb: 'How photovoltaic cells and solar systems work, sizing and the economics of an installation.',
  },
  {
    id: 'dtu-wind-energy',
    title: 'Wind Energy',
    provider: 'edX',
    partner: 'Technical University of Denmark (DTU)',
    category: 'engineering',
    subject: 'Energy engineering',
    level: 'Intermediate',
    hours: 30,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.edx.org/learn/energy/technical-university-of-denmark-dtu-wind-energy',
    blurb: 'Aerodynamics, turbine design and grid integration from a leading wind-power research group.',
  },
  {
    id: 'nptel-fluid-mechanics',
    title: 'Fluid Mechanics',
    provider: 'NPTEL',
    partner: 'IIT Kanpur',
    category: 'engineering',
    subject: 'Mechanical engineering',
    level: 'Advanced',
    hours: 48,
    cost: 'Free',
    certificate: true,
    trending: false,
    url: 'https://nptel.ac.in/courses/112104118',
    blurb: 'Statics and dynamics of fluids, from continuity and momentum to boundary layers.',
  },
  {
    id: 'nptel-strength-materials',
    title: 'Strength of Materials',
    provider: 'NPTEL',
    partner: 'IIT Kharagpur',
    category: 'engineering',
    subject: 'Civil engineering',
    level: 'Intermediate',
    hours: 40,
    cost: 'Free',
    certificate: true,
    trending: false,
    url: 'https://nptel.ac.in/courses/112105219',
    blurb: 'Stress, strain, bending and torsion, the mechanics behind every structural design.',
  },
  {
    id: 'khan-electrical-engineering',
    title: 'Electrical Engineering',
    provider: 'Khan Academy',
    partner: 'Khan Academy',
    category: 'engineering',
    subject: 'Electrical engineering',
    level: 'Beginner',
    hours: 20,
    cost: 'Free',
    certificate: false,
    trending: false,
    url: 'https://www.khanacademy.org/science/electrical-engineering',
    blurb: 'Circuit analysis, signals and semiconductors explained from scratch, free and self-paced.',
  },
  {
    id: 'ibm-devops-ci-cd',
    title: 'Introduction to DevOps',
    provider: 'Coursera',
    partner: 'IBM',
    category: 'engineering',
    subject: 'DevOps',
    level: 'Beginner',
    hours: 12,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/learn/introduction-to-devops',
    blurb: 'The culture and tooling of CI/CD, containers and infrastructure as code, from IBM.',
  },
  {
    id: 'cisco-networking-ccna',
    title: 'Networking Basics',
    provider: 'Cisco Networking Academy',
    partner: 'Cisco',
    category: 'engineering',
    subject: 'IT & networking',
    level: 'Beginner',
    hours: 30,
    cost: 'Free',
    certificate: true,
    trending: false,
    url: 'https://www.netacad.com/courses/networking/networking-basics',
    blurb: 'How networks move data, addressing and protocols, the first step toward CCNA.',
  },
  {
    id: 'edx-nanotech',
    title: 'Nanotechnology and Nanosensors',
    provider: 'edX',
    partner: 'Technion',
    category: 'engineering',
    subject: 'Materials & nano',
    level: 'Advanced',
    hours: 25,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.edx.org/learn/nanotechnology/technion-israel-institute-of-technology-nanotechnology-and-nanosensors-part-1',
    blurb: 'The physics of the nanoscale and the sensors it enables, from a leading materials institute.',
  },
  {
    id: 'nptel-power-systems',
    title: 'Power System Analysis',
    provider: 'NPTEL',
    partner: 'IIT Madras',
    category: 'engineering',
    subject: 'Electrical engineering',
    level: 'Advanced',
    hours: 40,
    cost: 'Free',
    certificate: true,
    trending: false,
    url: 'https://nptel.ac.in/courses/108106026',
    blurb: 'Load flow, fault analysis and stability for electrical power grids.',
  },
  {
    id: 'harvard-cs50-ai',
    title: "CS50's Introduction to Artificial Intelligence with Python",
    provider: 'edX',
    partner: 'Harvard University',
    category: 'engineering',
    subject: 'Artificial intelligence',
    level: 'Intermediate',
    hours: 60,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.edx.org/learn/artificial-intelligence/harvard-university-cs50-s-introduction-to-artificial-intelligence-with-python',
    blurb: 'Search, knowledge, optimisation, and machine learning implemented in Python, from Harvard.',
  },
  {
    id: 'gt-control-systems',
    title: 'Control of Mobile Robots',
    provider: 'Coursera',
    partner: 'Georgia Institute of Technology',
    category: 'engineering',
    subject: 'Control systems',
    level: 'Advanced',
    hours: 30,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/mobile-robot',
    blurb: 'Control theory applied to robots that move, from dynamics to hybrid systems.',
  },
  {
    id: 'imperial-maths-ml',
    title: 'Mathematics for Machine Learning Specialization',
    provider: 'Coursera',
    partner: 'Imperial College London',
    category: 'engineering',
    subject: 'Engineering mathematics',
    level: 'Intermediate',
    hours: 60,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/specializations/mathematics-machine-learning',
    blurb: 'Linear algebra, calculus and PCA, the mathematics engineering and ML both rest on.',
  },
];

/* --------------------------------------------------------------------- medical */

const medical: ExternalCourse[] = [
  {
    id: 'michigan-anatomy',
    title: 'Anatomy Specialization',
    provider: 'Coursera',
    partner: 'University of Michigan',
    category: 'medical',
    subject: 'Anatomy',
    level: 'Intermediate',
    hours: 60,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/specializations/anatomy',
    blurb: 'The musculoskeletal, cardiovascular, respiratory and nervous systems, taught with cadaver imagery.',
  },
  {
    id: 'yale-science-wellbeing',
    title: 'The Science of Well-Being',
    provider: 'Coursera',
    partner: 'Yale University',
    category: 'medical',
    subject: 'Health psychology',
    level: 'Beginner',
    hours: 19,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/learn/the-science-of-well-being',
    blurb: "Yale's most popular course ever: the psychology of happiness and habits that actually raise it.",
  },
  {
    id: 'stanford-food-health',
    title: 'Introduction to Food and Health',
    provider: 'Coursera',
    partner: 'Stanford University',
    category: 'medical',
    subject: 'Nutrition',
    level: 'Beginner',
    hours: 7,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/food-and-health',
    blurb: 'How modern diets drive chronic disease, and the evidence behind eating for long-term health.',
  },
  {
    id: 'jhu-covid-contact-tracing',
    title: 'COVID-19 Contact Tracing',
    provider: 'Coursera',
    partner: 'Johns Hopkins University',
    category: 'medical',
    subject: 'Public health',
    level: 'Beginner',
    hours: 6,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/covid-19-contact-tracing',
    blurb: 'How infectious-disease transmission and contact tracing work, from a top public-health school.',
  },
  {
    id: 'jhu-psychological-first-aid',
    title: 'Psychological First Aid',
    provider: 'Coursera',
    partner: 'Johns Hopkins University',
    category: 'medical',
    subject: 'Mental health',
    level: 'Beginner',
    hours: 6,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/learn/psychological-first-aid',
    blurb: 'Supporting people through crisis and disaster using the evidence-based RAPID model.',
  },
  {
    id: 'imperial-global-health',
    title: 'Global Master of Public Health — Global Health',
    provider: 'edX',
    partner: 'Imperial College London',
    category: 'medical',
    subject: 'Public health',
    level: 'Intermediate',
    hours: 24,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.edx.org/school/imperialx',
    blurb: 'The epidemiology of the diseases that shape population health, and how systems respond.',
  },
  {
    id: 'harvard-health-medicine',
    title: 'Health and Medicine courses',
    provider: 'Harvard Online',
    partner: 'Harvard University',
    category: 'medical',
    subject: 'Clinical & research',
    level: 'Intermediate',
    hours: 15,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://pll.harvard.edu/subject/health-medicine',
    blurb: "Harvard's catalogue of health and medicine courses, from clinical topics to research methods.",
  },
  {
    id: 'stanford-child-nutrition',
    title: 'Child Nutrition and Cooking',
    provider: 'Coursera',
    partner: 'Stanford University',
    category: 'medical',
    subject: 'Nutrition',
    level: 'Beginner',
    hours: 10,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/childnutrition',
    blurb: 'Evidence-based feeding of children, from a paediatrician, with practical cooking guidance.',
  },
  {
    id: 'umn-global-health-response',
    title: 'Global Health: Preparation, Detection, and Response',
    provider: 'Coursera',
    partner: 'University of Minnesota',
    category: 'medical',
    subject: 'Public health',
    level: 'Beginner',
    hours: 12,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/global-health-preparation-detection-response',
    blurb: 'Detecting outbreaks, emergency preparedness and coordinated public-health response.',
  },
  {
    id: 'duke-medical-neuroscience',
    title: 'Medical Neuroscience',
    provider: 'Coursera',
    partner: 'Duke University',
    category: 'medical',
    subject: 'Neuroscience',
    level: 'Advanced',
    hours: 85,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/medical-neuroscience',
    blurb: 'A full medical-school neuroscience course: the sensory, motor and cognitive brain in depth.',
  },
];

/* --------------------------------------------------------------- data science & AI */

const dataScience: ExternalCourse[] = [
  {
    id: 'ml-specialization-andrew-ng',
    title: 'Machine Learning Specialization',
    provider: 'Coursera',
    partner: 'DeepLearning.AI & Stanford',
    category: 'data-science',
    subject: 'Machine learning',
    level: 'Beginner',
    hours: 60,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/specializations/machine-learning-introduction',
    blurb: "Andrew Ng's rebuilt classic: regression, classification, neural nets and recommenders in Python.",
  },
  {
    id: 'deep-learning-specialization',
    title: 'Deep Learning Specialization',
    provider: 'Coursera',
    partner: 'DeepLearning.AI',
    category: 'data-science',
    subject: 'Deep learning',
    level: 'Intermediate',
    hours: 120,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/specializations/deep-learning',
    blurb: 'Neural networks, CNNs, sequence models and transformers, the standard deep-learning grounding.',
  },
  {
    id: 'ibm-data-science',
    title: 'IBM Data Science Professional Certificate',
    provider: 'Coursera',
    partner: 'IBM',
    category: 'data-science',
    subject: 'Data science',
    level: 'Beginner',
    hours: 180,
    cost: 'Paid',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/professional-certificates/ibm-data-science',
    blurb: 'A job-ready path: Python, SQL, analysis, visualisation and a machine-learning capstone.',
  },
  {
    id: 'google-data-analytics',
    title: 'Google Data Analytics Professional Certificate',
    provider: 'Coursera',
    partner: 'Google',
    category: 'data-science',
    subject: 'Data analytics',
    level: 'Beginner',
    hours: 180,
    cost: 'Paid',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/professional-certificates/google-data-analytics',
    blurb: 'Spreadsheets, SQL, R and Tableau for analysis, one of the most-enrolled certificates anywhere.',
  },
  {
    id: 'genai-for-everyone',
    title: 'Generative AI for Everyone',
    provider: 'Coursera',
    partner: 'DeepLearning.AI',
    category: 'data-science',
    subject: 'Generative AI',
    level: 'Beginner',
    hours: 6,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/learn/generative-ai-for-everyone',
    blurb: 'Andrew Ng on what generative AI can and cannot do, and how to use it well in real work.',
  },
  {
    id: 'chatgpt-prompt-engineering',
    title: 'ChatGPT Prompt Engineering for Developers',
    provider: 'DeepLearning.AI',
    partner: 'DeepLearning.AI & OpenAI',
    category: 'data-science',
    subject: 'Generative AI',
    level: 'Intermediate',
    hours: 3,
    cost: 'Free',
    certificate: false,
    trending: true,
    url: 'https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/',
    blurb: 'Prompting patterns for building with LLMs, free, taught by Isa Fulford and Andrew Ng.',
  },
  {
    id: 'ibm-python-data-science',
    title: 'Python for Data Science, AI & Development',
    provider: 'Coursera',
    partner: 'IBM',
    category: 'data-science',
    subject: 'Programming',
    level: 'Beginner',
    hours: 25,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/python-for-applied-data-science-ai',
    blurb: 'Python plus pandas, NumPy and APIs, aimed squarely at data and AI work.',
  },
  {
    id: 'jhu-r-programming',
    title: 'R Programming',
    provider: 'Coursera',
    partner: 'Johns Hopkins University',
    category: 'data-science',
    subject: 'Statistical computing',
    level: 'Intermediate',
    hours: 57,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/r-programming',
    blurb: 'R for real statistical work, part of the long-running Data Science specialization.',
  },
  {
    id: 'tensorflow-developer',
    title: 'DeepLearning.AI TensorFlow Developer Professional Certificate',
    provider: 'Coursera',
    partner: 'DeepLearning.AI',
    category: 'data-science',
    subject: 'Deep learning',
    level: 'Intermediate',
    hours: 65,
    cost: 'Paid',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/professional-certificates/tensorflow-in-practice',
    blurb: 'Build and train neural networks in TensorFlow for vision, text and sequences.',
  },
  {
    id: 'fast-ai-practical-dl',
    title: 'Practical Deep Learning for Coders',
    provider: 'fast.ai',
    partner: 'fast.ai',
    category: 'data-science',
    subject: 'Deep learning',
    level: 'Intermediate',
    hours: 50,
    cost: 'Free',
    certificate: false,
    trending: true,
    url: 'https://course.fast.ai/',
    blurb: 'A top-down, code-first deep-learning course that gets you training real models fast, free.',
  },
  {
    id: 'mit-intro-deep-learning',
    title: '6.S191 Introduction to Deep Learning',
    provider: 'MIT',
    partner: 'MIT',
    category: 'data-science',
    subject: 'Deep learning',
    level: 'Intermediate',
    hours: 15,
    cost: 'Free',
    certificate: false,
    trending: false,
    url: 'http://introtodeeplearning.com/',
    blurb: "MIT's fast-paced intro to deep learning, with lecture videos and labs refreshed each year.",
  },
  {
    id: 'ibm-ai-engineering',
    title: 'IBM AI Engineering Professional Certificate',
    provider: 'Coursera',
    partner: 'IBM',
    category: 'data-science',
    subject: 'Machine learning',
    level: 'Intermediate',
    hours: 130,
    cost: 'Paid',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/professional-certificates/ai-engineer',
    blurb: 'Building and deploying ML and deep-learning models with scikit-learn, Keras and PyTorch.',
  },
];

/* -------------------------------------------------------------------- business */

const business: ExternalCourse[] = [
  {
    id: 'wharton-business-foundations',
    title: 'Business Foundations Specialization',
    provider: 'Coursera',
    partner: 'University of Pennsylvania (Wharton)',
    category: 'business',
    subject: 'General management',
    level: 'Beginner',
    hours: 60,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/specializations/wharton-business-foundations',
    blurb: 'Marketing, finance, accounting and operations, the core of an MBA first year, from Wharton.',
  },
  {
    id: 'google-project-management',
    title: 'Google Project Management Professional Certificate',
    provider: 'Coursera',
    partner: 'Google',
    category: 'business',
    subject: 'Project management',
    level: 'Beginner',
    hours: 150,
    cost: 'Paid',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/professional-certificates/google-project-management',
    blurb: 'Agile, Scrum and traditional project management to a job-ready standard, built by Google.',
  },
  {
    id: 'google-digital-marketing',
    title: 'Google Digital Marketing & E-commerce Professional Certificate',
    provider: 'Coursera',
    partner: 'Google',
    category: 'business',
    subject: 'Marketing',
    level: 'Beginner',
    hours: 180,
    cost: 'Paid',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce',
    blurb: 'Email, search, social and e-commerce marketing, with hands-on tools and a portfolio.',
  },
  {
    id: 'yale-financial-markets',
    title: 'Financial Markets',
    provider: 'Coursera',
    partner: 'Yale University',
    category: 'business',
    subject: 'Finance',
    level: 'Beginner',
    hours: 33,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/financial-markets-global',
    blurb: 'Robert Shiller on risk, insurance, banking and how markets really behave.',
  },
  {
    id: 'wharton-intro-marketing',
    title: 'Introduction to Marketing',
    provider: 'Coursera',
    partner: 'University of Pennsylvania (Wharton)',
    category: 'business',
    subject: 'Marketing',
    level: 'Beginner',
    hours: 10,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/wharton-marketing',
    blurb: 'Branding, customer centricity and go-to-market, the fundamentals of modern marketing.',
  },
  {
    id: 'illinois-financial-accounting',
    title: 'Fundamentals of Accounting Specialization',
    provider: 'Coursera',
    partner: 'University of Illinois',
    category: 'business',
    subject: 'Accounting',
    level: 'Intermediate',
    hours: 80,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/specializations/accounting-fundamentals',
    blurb: 'Financial and managerial accounting from the ground up, from a top-ranked accounting faculty.',
  },
  {
    id: 'macquarie-excel-skills',
    title: 'Excel Skills for Business Specialization',
    provider: 'Coursera',
    partner: 'Macquarie University',
    category: 'business',
    subject: 'Business tools',
    level: 'Beginner',
    hours: 96,
    cost: 'Free to audit',
    certificate: true,
    trending: true,
    url: 'https://www.coursera.org/specializations/excel',
    blurb: 'Excel from essentials to advanced formulas, pivot tables and dashboards, business-focused.',
  },
  {
    id: 'wharton-entrepreneurship',
    title: 'Entrepreneurship Specialization',
    provider: 'Coursera',
    partner: 'University of Pennsylvania (Wharton)',
    category: 'business',
    subject: 'Entrepreneurship',
    level: 'Intermediate',
    hours: 60,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/specializations/wharton-entrepreneurship',
    blurb: 'Opportunity, launch, growth and financing, taking an idea to a fundable venture.',
  },
  {
    id: 'macquarie-leading',
    title: 'Leading: Human Resource Management and Leadership',
    provider: 'Coursera',
    partner: 'Macquarie University',
    category: 'business',
    subject: 'Leadership',
    level: 'Intermediate',
    hours: 55,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/specializations/hr-management-leadership',
    blurb: 'Managing and leading people, from motivation and teams to organisational change.',
  },
  {
    id: 'darden-business-strategy',
    title: 'Business Strategy Specialization',
    provider: 'Coursera',
    partner: 'University of Virginia (Darden)',
    category: 'business',
    subject: 'Strategy',
    level: 'Intermediate',
    hours: 40,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/specializations/business-strategy',
    blurb: 'Competitive advantage, industry analysis and strategic decision-making, with case studies.',
  },
  {
    id: 'michigan-negotiation',
    title: 'Successful Negotiation: Essential Strategies and Skills',
    provider: 'Coursera',
    partner: 'University of Michigan',
    category: 'business',
    subject: 'Negotiation',
    level: 'Beginner',
    hours: 17,
    cost: 'Free to audit',
    certificate: true,
    trending: false,
    url: 'https://www.coursera.org/learn/negotiation-skills',
    blurb: 'A repeatable four-step negotiation process, useful in deals, salary and everyday work.',
  },
];

/* --------------------------------------------------------------------- the catalogue */

/** Every course, in category order. This is the array pages and helpers read from. */
export const courseLibrary: ExternalCourse[] = [
  ...engineering,
  ...medical,
  ...dataScience,
  ...business,
];

/** Human-readable label for each category, for filter chips and headings. */
export const categoryLabels: Record<CourseCategory, string> = {
  engineering: 'Engineering',
  medical: 'Medical & Health',
  'data-science': 'Data Science & AI',
  business: 'Business & Management',
};

/** The category ids in display order, so a filter bar renders the same way everywhere. */
export const categoryOrder: CourseCategory[] = ['engineering', 'medical', 'data-science', 'business'];

/** How many courses sit under each category. Derived from the data, never hardcoded. */
export function categoryCounts(): Record<CourseCategory, number> {
  const counts = { engineering: 0, medical: 0, 'data-science': 0, business: 0 } as Record<CourseCategory, number>;
  for (const course of courseLibrary) counts[course.category] += 1;
  return counts;
}

/** Courses in one category, or all of them. */
export function coursesInCategory(category: CourseCategory | 'all'): ExternalCourse[] {
  return category === 'all' ? courseLibrary : courseLibrary.filter((course) => course.category === category);
}

/** The trending set, across every category, for the "Trending now" view. */
export function trendingCourses(): ExternalCourse[] {
  return courseLibrary.filter((course) => course.trending);
}

/** "1h", "6h", "180h" — the duration as the card prints it. Every course is at least 1h. */
export function courseHoursLabel(hours: number): string {
  return `${hours}h`;
}

/**
 * A reminder, not a runtime check. The sandbox has no outbound network and a live link
 * probe belongs in a deploy step, not a unit test that would flake whenever a provider
 * had a slow day. Before a public launch, curl -I -L each `url` and confirm a 200; a 404
 * or a redirect to a catalogue root means the course moved and the row needs updating.
 */
export const verifyLinks =
  'Re-check every course URL before a public launch — providers retire and restructure courses. A link that redirects to a catalogue root has moved.';
